---
image: hashicorp/terraform:latest

# NOTE - New accounts must be initialized outside of GitLab CI/CD
# to setup the S3 state bucket and DynamoDB lock table.
# See bin/aws_init

variables:
  # Remianing items should be defined in project variables
  AWS_ACCESS_KEY_ID: setme
  AWS_SECRET_ACCESS_KEY: setme
  AWS_ACOUNT_ID: setme
  AWS_DEFAULT_REGION: setme
  TF_VAR_infra_name: setme
  TF_VAR_root_zone: setme
  TF_VAR_static_site_fqdn: setme
  TF_VAR_static_dns_record_file: setme_as_file

stages:
  - test
  - build
  - deploy

before_script:
  # Default setup for most stages
  - mkdir -p plans
  - . bin/commonlib
  - init_tf_vars $TF_VAR_infra_name $CI_ENVIRONMENT_NAME
  - cd stacks/$CI_ENVIRONMENT_NAME
  - terraform init
    -backend-config="bucket=${TF_VAR_state_bucket}"
    -backend-config="key=${TF_VAR_stack_name}"
    -backend-config="dynamodb_table=${TF_VAR_lock_table}"
    -backend-config="region=${TF_VAR_region}"

# Universal stages
test:fmt:
  stage: test
  before_script: []
  script:
    - terraform fmt -recursive -diff -check

# Run tfsec on everything at
test:tfsec:
  stage: test
  image: tfsec/tfsec-ci
  before_script:
    - . bin/commonlib
    - init_tf_vars $TF_VAR_infra_name account
  script:
    - tfsec stacks

# Templates
.plan:
  script:
    - terraform plan -detailed-exitcode
      -out ${CI_PROJECT_DIR}/plans/${CI_ENVIRONMENT_NAME}.plan
      || exit_code=$?
    - case $exit_code in
        1) exit 1;;
        2) echo "CHANGED=true" >> ${CI_PROJECT_DIR}/changed.env;;
        *) echo "CHANGED=false" >> ${CI_PROJECT_DIR}/changed.env;;
      esac
  artifacts:
    paths:
      # Saved plans
      - plans
      # Local copy of .terraform dir
      - stacks/${CI_ENVIRONMENT_NAME}/.terraform
      # Zipped function code
      - functions/*.zip
    reports:
      dotenv: changed.env

.apply:
  script:
    - terraform apply -auto-approve
      ${CI_PROJECT_DIR}/plans/${CI_ENVIRONMENT_NAME}.plan
    
# Prod account level resources
plan:account:
  extends: .plan
  environment: account
  stage: build

apply:account:
  extends: .apply
  environment: account
  stage: deploy
  needs:
    - job: plan:account
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CHANGED == "true"'
      when: manual

# Static web site
plan:web:
  extends: .plan
  environment: web
  stage: build

apply:web:
  extends: .apply
  environment: web
  stage: deploy
  needs:
    - job: plan:web
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CHANGED == "true"'
