---
image: hashicorp/terraform:latest

# NOTE - New accounts must be initialized outside of GitLab CI/CD
# to setup the S3 state bucket and DynamoDB lock table.
# See bin/aws_init

variables:
  # Remianing items should be defined in project variables
  AWS_ACCESS_KEY_ID: setme
  AWS_SECRET_ACCESS_KEY: setme
  AWS_ACOUNT_ID: setme
  AWS_DEFAULT_REGION: setme
  TF_VAR_infra_name: setme
  TF_VAR_root_zone: setme
  TF_VAR_static_site_fqdn: setme
  TF_VAR_static_dns_record_file: setme_as_file

stages:
  - test
  - build
  - deploy

before_script:
  # Default setup for most stages
  - mkdir -p plans
  - . bin/commonlib
  - init_tf_vars $TF_VAR_infra_name $CI_ENVIRONMENT_NAME
  - cd stacks/$CI_ENVIRONMENT_NAME
  - terraform init
    -backend-config="bucket=${TF_VAR_state_bucket}"
    -backend-config="key=${TF_VAR_stack_name}"
    -backend-config="dynamodb_table=${TF_VAR_lock_table}"
    -backend-config="region=${TF_VAR_region}"

# Universal stages
check_fmt:
  stage: test
  before_script: []
  script:
    - terraform fmt -recursive -diff -check

# Templates
.tfsec:
  image: tfsec/tfsec-ci
  before_script:
    - . bin/commonlib
    - init_tf_vars $TF_VAR_infra_name $CI_ENVIRONMENT_NAME
  script:
    - tfsec stacks/$CI_ENVIRONMENT_NAME

.plan:
  script:
    - terraform plan -detailed-exitcode
      -out ${CI_PROJECT_DIR}/plans/${CI_ENVIRONMENT_NAME}.plan
      || exit_code=$?
    - case $exit_code in
        1) exit 1;;
        2) echo "CHANGED=true" >> ${CI_PROJECT_DIR}/changed.env;;
        *) echo "CHANGED=false" >> ${CI_PROJECT_DIR}/changed.env;;
      esac
  artifacts:
    paths:
      # Saved plans
      - plans
      # Local copy of .terraform dir
      - stacks/${CI_ENVIRONMENT_NAME}/.terraform
      # Zipped function code
      - functions/*.zip
    reports:
      dotenv: changed.env

.apply:
  script:
    - terraform apply -auto-approve
      ${CI_PROJECT_DIR}/plans/${CI_ENVIRONMENT_NAME}.plan
  only:
    variables:
      - $CHANGED == "true"
    
# Prod account level resources
account:tfsec:
  extends: .tfsec
  environment: account
  stage: test

account:plan:
  extends: .plan
  environment: account
  stage: build
  needs:
    - job: account:tfsec

account:apply:
  extends: .apply
  environment: account
  stage: deploy
  needs:
    - job: account:plan
      artifacts: true
  when: manual
  only:
    - main

# Static web site
web:tfsec:
  extends: .tfsec
  environment: web
  stage: test

web:plan:
  extends: .plan
  environment: web
  stage: build
  needs:
    - job: web:tfsec

web:apply:
  extends: .apply
  environment: web
  stage: deploy
  needs:
    - job: web:plan
      artifacts: true
  only:
    - main
